openapi: 3.0.0
info:
  title: STD23063 - TD1
  version: 1.0.0
  description: API pour un restaurant

servers:
  - url: https://localhost.STD23063.com

paths:
  /customers:
    get:
      summary: Récupérer la liste des clients
      responses:
        '200':
          description: Liste des clients récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'

components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        yearsOld:
          type: integer

